
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR msp430)
set(CMAKE_CROSSCOMPILING 1)

set(MSP430_COMPILER_PREFIX "msp430-elf-" CACHE STRING "Compiler prefix")
set(MSP430_MCU "msp430g2553" CACHE STRING "Target MCU name")

set(CMAKE_C_COMPILER "${MSP430_COMPILER_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${MSP430_COMPILER_PREFIX}g++")

set(GCC_FLAGS "-mmcu=${MCU}")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${GCC_FLAGS}" CACHE STRING "C compiler flags")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GCC_FLAGS}" CACHE STRING "C++ compiler flags")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${GCC_FLAGS}" CACHE STRING "Assembler flags")
